(* begin-documentation-root
###########
  Welcome
###########


.. toctree::
   :maxdepth: 2
   :caption: Integrated Oberon:
   :hidden:

   Welcome           <Welcome.rst>
   ../Boot/ORLinker  <Installation.rst>
   ../Assist/Hello   <Hello.rst>
   ../Build/Explore  <Development.rst>
   ../Net/Report     <Community.rst>
   ../Doc/Doc        <Conduct.rst>

What is Integrated Oberon
=========================

A system based on Oberon the language and Oberon the OS

Integrating features, functions and capabilities from other systems

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

end-documentation-root *)

(* begin-documentation-node
###############
Code of Conduct
###############

Be excellent to each other. Borrowing from the Python project:

Diversity
=========
Diversity Statement
-------------------
The IO-Core and the IO community welcome and encourage participation by everyone. Our community is based on mutual respect, tolerance, and encouragement, and we are working to help each other live up to these principles. We want our community to be more diverse: whoever you are, and whatever your background, we welcome you.

Diversity Appendix
------------------
We have created this diversity statement because we believe that a diverse IO community is stronger and more vibrant. A diverse community where people treat each other with respect has more potential contributors and more sources for ideas.

Although we have phrased the formal diversity statement generically to make it all-inclusive, we recognize that there are specific attributes that are used to discriminate against people. In alphabetical order, some of these attributes include (but are not limited to): age, culture, ethnicity, gender identity or expression, national origin, physical or mental difference, politics, race, religion, sex, sexual orientation, socio-economic status, and subculture. We welcome people regardless of the values of these or other attributes.

The IO community welcomes people no matter what languages they are fluent in. (Although core IO development is done in English.)

end-documentation-node *)

(* begin-package-description
### _Package Overview:_
The Doc package manages:
* Generating documentation from Oberon package sources
* Browsing (eventually) Oberon documentation
### _Package Use:_

USAGE:
```
# from external system with python and sphinx

make extract; make clean; make html

```

### _Modules in this package:_
end-package-description *)

(* begin-module-use-description
Module Doc handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Doc; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Doc.
